import{CONFIG}from'./config.js';import{fetchDashboardData,saveRowUpdate}from'./services/api.js';import{applyGlobalFilters,PRESETS}from'./services/filters.js';import{esc,n,num,fmt}from'./services/utils.js';import{fetchDashboard as fetchLiveDashboard,fetchTrends,fetchAlerts}from'./services/external.js';import*as Executive from'./components/Executive.js';import*as Analytics from'./components/Analytics.js';import*as Operation from'./components/Operation.js';import*as Master from'./components/Master.js';import*as Metadata from'./components/Metadata.js';import*as Keywords from'./components/Keywords.js';import*as Redirects from'./components/Redirects.js';import*as Protected from'./components/Protected.js';import*as Checklist from'./components/Checklist.js';import*as Setup from'./components/Setup.js';
const C={executive:Executive,analytics:Analytics,operation:Operation,master:Master,metadata:Metadata,keywords:Keywords,redirects:Redirects,protected:Protected,checklist:Checklist,setup:Setup};const s={currentView:'executive',activePreset:'all',data:{master:[],metadata:[],keywords:[],redirects:[],protected:[],issues:[],checklist:[]},filtered:[],selected:null,checkState:{},filters:{search:'',priority:'',action:'',type:'',meta:'',qa:'',http:''},external:{kpis:{},trends:{gsc:[],ga4:[],clarity:[]},alerts:[],lastUpdated:null,loading:false}};const $=id=>document.getElementById(id);const toast=m=>{const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2400)};const setStatus=(m,t='loading')=>{$('status').className='status '+t;$('status').textContent=m};function setTheme(t){localStorage.setItem('hito_theme',t);document.body.classList.toggle('dark',t==='dark');document.querySelectorAll('.theme button').forEach(b=>b.classList.toggle('active',b.dataset.theme===t))}
function presets(){ $('presets').innerHTML=Object.entries(PRESETS).map(([k,p])=>`<button class="chip ${s.activePreset===k?'active':''}" data-preset="${k}">${p.label}</button>`).join('')}
function setView(v){s.currentView=v;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));render()}
function fillSelect(id,vals){const el=$(id),first=el.options[0].outerHTML;el.innerHTML=first+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}function hydrate(){const u=f=>[...new Set(s.data.master.map(r=>n(r[f])).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));fillSelect('priority',u('priority'));fillSelect('action',u('action'));fillSelect('type',u('type'));fillSelect('meta',u('metaStatus'));fillSelect('qa',u('qa'));fillSelect('http',[...new Set(s.data.master.map(r=>String(num(r.status)||'')).filter(Boolean))])}
function sync(){s.filters={search:$('q').value,priority:$('priority').value,action:$('action').value,type:$('type').value,meta:$('meta').value,qa:$('qa').value,http:$('http').value}}
function apply(){sync();s.filtered=applyGlobalFilters(s);if(!s.selected&&s.filtered.length)s.selected=s.filtered[0];render()}
function render(){const cmp=C[s.currentView]||C.executive;$('viewTitle').textContent=cmp.meta.title;$('viewSubtitle').textContent=cmp.meta.subtitle;$('root').innerHTML=cmp.render(s);bind()}
function bind(){document.querySelectorAll('[data-select-url]').forEach(el=>el.onclick=()=>{const url=decodeURIComponent(el.dataset.selectUrl);s.selected=s.data.master.find(r=>r.url===url)||s.filtered.find(r=>r.url===url)||s.selected;if(s.currentView!=='master')setView('master');else render()});document.querySelectorAll('[data-toggle-task]').forEach(el=>el.onclick=e=>{e.stopPropagation();const i=Number(el.dataset.toggleTask);s.checkState[i]=!s.checkState[i];toast(s.checkState[i]?'Tarea aprobada':'Tarea desmarcada');render()});const b=$('detailEditBtn');if(b)b.onclick=openEdit}
async function load(){try{setStatus('Cargando datos desde Google Sheets...','loading');s.data=await fetchDashboardData();s.data.checklist.forEach((t,i)=>{if(s.checkState[i]===undefined)s.checkState[i]=/aprobado/i.test(t.status)});hydrate();s.filtered=applyGlobalFilters(s);s.selected=s.filtered[0]||null;presets();render();setStatus(`Datos actualizados: ${fmt.format(s.data.master.length)} URLs · ${fmt.format(s.data.redirects.length)} redirects · ${new Date().toLocaleTimeString('es-AR')}`,'ok');toast('Datos actualizados');// Cargar datos de APIs externas en segundo plano
loadExternalData()}catch(e){console.error(e);setStatus('No se pudo cargar la data. Revisá DATA_URL o Apps Script.','error');toast('Error al cargar datos')}}

/**
 * Cargar datos en vivo desde el backend (GSC, GA4, Clarity)
 */
async function loadExternalData() {
  if (s.external.loading) return;
  s.external.loading = true;

  try {
    const [dashboard, trends, alerts] = await Promise.all([
      fetchLiveDashboard(),
      fetchTrends(30),
      fetchAlerts('active'),
    ]);

    s.external.kpis = dashboard.kpis;
    s.external.trends = trends;
    s.external.alerts = alerts.alerts || [];
    s.external.lastUpdated = new Date();
    s.external.loading = false;

    render();
    console.log('[External] Live data loaded:', dashboard.kpis);
  } catch (e) {
    s.external.loading = false;
    console.warn('[External] Error loading live data:', e.message);
    // No mostrar error al usuario, los datos de Sheets ya cargaron
  }
}
function modalNotice(msg,type='loading'){const el=$('modalNotice');if(!el)return;el.className='modalNotice '+type;el.textContent=msg}
function ensureOption(id,value){const el=$(id);if(!el||!value||[...el.options].some(o=>o.value===value))return;const opt=document.createElement('option');opt.value=value;opt.textContent=value;el.appendChild(opt)}
function populateModalOptions(){const target=$('fTargetSelect');if(target){const urls=[...new Set(s.data.master.map(r=>r.url).filter(Boolean))].slice(0,1200);target.innerHTML='<option value="">Seleccionar destino existente o mantener manual</option>'+urls.map(u=>`<option value="${esc(u)}">${esc(u)}</option>`).join('');target.onchange=()=>{if(target.value)$('fTarget').value=target.value}}const dl=$('kwOptions');if(dl){const kws=[...new Set(s.data.keywords.map(r=>r.kw).concat(s.data.master.map(r=>r.kw)).filter(Boolean))].slice(0,600);dl.innerHTML=kws.map(k=>`<option value="${esc(k)}"></option>`).join('')}}
function applyTemplate(){const type=$('fTemplate')?.value;if(!type||!s.selected)return;const kw=$('fKwTarget').value||s.selected.kw||'keyword objetivo';const base=s.selected.title||s.selected.type||'HitOcean';const templates={service:`${kw} | HitOcean`,blog:`${base} - Guía y mejores prácticas | HitOcean`,location:`${kw} en LATAM | HitOcean`,brand:`${base} | HitOcean`};if(!$('fTitleNew').value)$('fTitleNew').value=templates[type]||'';if(!$('fDescriptionNew').value)$('fDescriptionNew').value=`Conocé cómo HitOcean ayuda a empresas a mejorar sus resultados con ${kw}. Soluciones tech, IA, ciberseguridad y equipos especializados para escalar.`}
function openEdit(){const r=s.selected;if(!r){toast('Primero seleccioná una URL');return}populateModalOptions();ensureOption('fAction',r.action);ensureOption('fPriority',r.priority);ensureOption('fMeta',r.metaStatus);ensureOption('fQa',r.qa);$('editTarget').textContent=r.url;$('fUrl').value=r.url||'';$('fPriority').value=r.priority||'';$('fAction').value=r.action||'';$('fTarget').value=r.target||'';$('fTargetSelect').value=r.target||'';$('fKwTarget').value=r.kwTarget||'';$('fTitleNew').value=r.titleNew||'';$('fDescriptionNew').value=r.descriptionNew||'';$('fMeta').value=r.metaStatus||'';$('fQa').value=r.qa||'';$('fNotes').value=r.notes||'';modalNotice('Editá los campos y guardá. El cambio se enviará a Google Sheets.','loading');$('modal').classList.add('show')}
function closeEdit(){$('modal').classList.remove('show')}
async function save(){if(!s.selected)return;const updates={'Prioridad':$('fPriority').value,'Acción sugerida':$('fAction').value,'URL nueva / destino':$('fTarget').value,'KW objetivo nueva':$('fKwTarget').value,'Title nuevo Astro':$('fTitleNew').value,'Description nueva Astro':$('fDescriptionNew').value,'Checklist metadata':$('fMeta').value,'QA migración':$('fQa').value,'Notas':$('fNotes').value};$('save').disabled=true;$('save').textContent='Guardando...';modalNotice('Guardando cambios en Google Sheets...','loading');try{await saveRowUpdate(s.selected.url,updates);localUpdate(s.selected.url,updates);s.filtered=applyGlobalFilters(s);render();modalNotice('Dato guardado con éxito. La vista ya fue actualizada.','ok');toast('Dato guardado con éxito en Google Sheets');setTimeout(closeEdit,850)}catch(e){console.error(e);modalNotice('Error al guardar. Revisá doPost(e), permisos o columnas editables.','error');toast('Error al guardar. Revisá doPost(e).')}finally{$('save').disabled=false;$('save').textContent='Guardar cambios'}}
function localUpdate(url,u){const map={'Prioridad':'priority','Acción sugerida':'action','URL nueva / destino':'target','KW objetivo nueva':'kwTarget','Title nuevo Astro':'titleNew','Description nueva Astro':'descriptionNew','Checklist metadata':'metaStatus','QA migración':'qa','Notas':'notes'};s.data.master.forEach(r=>{if(r.url===url)Object.entries(map).forEach(([col,key])=>r[key]=u[col])});s.selected=s.data.master.find(r=>r.url===url)||s.selected}
function exportCSV(){const h=['URL','Tipo','Prioridad','Acción','Destino','HTTP','Clicks','Impressions','Position','Title','Description','KW','KW Astro','Title Astro','Description Astro','Metadata','QA','Issues','Notas'];const rows=s.filtered.map(r=>[r.url,r.type,r.priority,r.action,r.target,r.status,num(r.clicks),num(r.impressions),num(r.position),r.title,r.description,r.kw,r.kwTarget,r.titleNew,r.descriptionNew,r.metaStatus,r.qa,r.issues,r.notes]);const csv=[h,...rows].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href='data:text/csv;charset=utf-8,\uFEFF'+encodeURIComponent(csv);a.download=`hitocean_${s.currentView}_filtered.csv`;a.click();toast('CSV exportado')}
function clear(){['q','priority','action','type','meta','qa','http'].forEach(id=>$(id).value='');s.activePreset='all';presets();apply()}
function init(){setTheme(localStorage.getItem('hito_theme')||'light');$('sheet').href=CONFIG.SHEET_URL;$('refresh').onclick=load;$('refreshLive')&&($('refreshLive').onclick=loadExternalData);$('edit').onclick=openEdit;$('export').onclick=exportCSV;$('clear').onclick=clear;$('closeModal').onclick=closeEdit;$('cancel').onclick=closeEdit;$('save').onclick=save;if($('fTemplate'))$('fTemplate').onchange=applyTemplate;$('modal').onclick=e=>{if(e.target.id==='modal')closeEdit()};document.querySelectorAll('.theme button').forEach(b=>b.onclick=()=>setTheme(b.dataset.theme));document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));['q','priority','action','type','meta','qa','http'].forEach(id=>{$(id).oninput=apply;$(id).onchange=apply});$('presets').onclick=e=>{const b=e.target.closest('[data-preset]');if(!b)return;s.activePreset=b.dataset.preset;presets();apply()};load()}init();