
let DATA={master:[],keywords:[],redirects:[],top:[],issues:[],checklist:[]};let filtered=[];let filtersReady=false;
const colors=['#2563eb','#16a34a','#f59e0b','#dc2626','#7c3aed','#0f766e','#334155','#0891b2','#be123c'];const fmt=new Intl.NumberFormat('es-AR');
const norm=v=>(v??'').toString().trim();function num(v){if(typeof v==='number')return v;return Number(norm(v).replace(/\./g,'').replace(',','.').replace('%','')||0)||0}
function esc(s){return norm(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function hostPath(url){try{return new URL(url).pathname||'/'}catch(e){return url}}function pill(t,c='gray'){return`<span class="pill ${c}">${esc(t||'—')}</span>`}
function priorityClass(p){p=norm(p).toLowerCase();if(p.includes('alta')||p.includes('high'))return'alta';if(p.includes('media')||p.includes('medium'))return'media';if(p.includes('baja')||p.includes('low'))return'baja';return'gray'}
function countBy(arr,key){const c={};arr.forEach(r=>{const k=norm(typeof key==='function'?key(r):r[key])||'Sin dato';c[k]=(c[k]||0)+1});return Object.entries(c).sort((a,b)=>b[1]-a[1])}
function sum(arr,key){return arr.reduce((a,r)=>a+num(r[key]),0)}function setStatus(m,t='loading'){const b=document.getElementById('statusBox');b.className=`status ${t}`;b.textContent=m}
async function loadData(){if(!CONFIG.DATA_URL||CONFIG.DATA_URL.includes('PEGAR_AQUI')){setStatus('Falta configurar DATA_URL en config.js','error');loadFallbackEmpty();return}try{setStatus('Cargando datos desde Google Sheets...','loading');const res=await fetch(CONFIG.DATA_URL,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);DATA=normalizeApiData(await res.json());setStatus(`Datos actualizados: ${fmt.format(DATA.master.length)} URLs cargadas`,'ok');boot()}catch(e){console.error(e);setStatus('No se pudo cargar el JSON. Revisá Apps Script, permisos y DATA_URL.','error');loadFallbackEmpty()}}
function reloadData(){filtersReady=false;loadData()}function loadFallbackEmpty(){DATA={master:[],keywords:[],redirects:[],top:[],issues:[],checklist:defaultChecklist()};boot()}
function pick(row,names){for(const n of names){if(row[n]!==undefined&&row[n]!==null&&row[n]!=='')return row[n]}const keys=Object.keys(row);for(const n of names){const t=n.toLowerCase().replace(/\s+/g,'');const f=keys.find(k=>k.toLowerCase().replace(/\s+/g,'')===t);if(f&&row[f]!=='')return row[f]}return''}
function inferMetadataStatus(title,desc){const t=norm(title),d=norm(desc);if(!t&&!d)return'Falta title y description';if(!t)return'Falta title';if(!d)return'Falta description';if(t.length<30||t.length>65||d.length<120||d.length>170)return'Optimizar';return'OK'}
function normalizeApiData(raw){const s=raw.sheets||raw;const masterRows=s.master||s["Master SEO Migración"]||s["Master SEO Metadata"]||s["URL Mapping Master"]||[];const keywordRows=s.keywords||s["Keyword Mapping"]||[];const redirectRows=s.redirects||s["Redirects Review"]||s["Redirects Draft"]||[];const topRows=s.top||s["Top URLs Protegidas"]||s["Top Protected URLs"]||[];const issueRows=s.issues||s["Issues Summary"]||s["Issues Detectados"]||[];const checklistRows=s.checklist||s["Checklist Ejecución"]||s["Checklist Migración"]||[];
const master=masterRows.map(row=>{const url=pick(row,['URL','URL actual','Address','Page URL','Final URL','Landing Page']);const title=pick(row,['Title actual','Meta title actual','Page Title','Title 1','Title']);const desc=pick(row,['Description actual','Meta description actual','Meta Description','Meta Description 1','Description']);return{url,type:pick(row,['Tipo','Type','Page Type']),priority:pick(row,['Prioridad SEO','Prioridad','Priority']),action:pick(row,['Acción sugerida','Acción','Action']),status:pick(row,['HTTP Status','Status Code','Status','Código']),clicks:pick(row,['Clics GSC','Clicks','Clics']),impressions:pick(row,['Impresiones GSC','Impressions','Impresiones']),position:pick(row,['Posición GSC','Average Position','Posición']),ctr:pick(row,['CTR']),kw:pick(row,['Keyword principal','KW detectada','Top Keyword','Keyword','Keyword inferida']),title,titleLen:pick(row,['Title Length','Title Len','Len Title','Longitud title'])||title.length,description:desc,descriptionLen:pick(row,['Description Length','Meta Description Length','Len Description','Longitud description'])||desc.length,metaStatus:pick(row,['Estado Metadata','Metadata Status','Checklist metadata'])||inferMetadataStatus(title,desc),schema:pick(row,['Schema','JSON-LD','Structured Data','Schema recomendado']),canonical:pick(row,['Canonical','Canonical Link Element 1','Canonical actual']),issues:pick(row,['Issues','Issue','Problemas','Notas SEO']),qa:pick(row,['QA','QA Status','Estado QA'])||'Pendiente',target:pick(row,['URL nueva','Nueva URL','Destino','Target URL'])}}).filter(r=>r.url);
const keywords=(keywordRows.length?keywordRows:master.filter(r=>r.kw)).map(row=>({url:pick(row,['URL','URL actual','Landing Page','Page URL'])||row.url,priority:pick(row,['Prioridad','Prioridad SEO'])||row.priority,kw:pick(row,['Keyword','KW detectada','Keyword principal','Top Keyword'])||row.kw,intent:pick(row,['Intent','Intención']),kwPosition:pick(row,['Posición','Position','Posición actual'])||row.position,volume:pick(row,['Volume','Volumen']),clicks:pick(row,['Clicks','Clics','Clics GSC'])||row.clicks,impressions:pick(row,['Impressions','Impresiones','Impresiones GSC'])||row.impressions,target:pick(row,['KW objetivo nueva','Keyword objetivo','Target Keyword'])})).filter(r=>r.url||r.kw);
const redirects=(redirectRows.length?redirectRows:master.filter(r=>norm(r.action).match(/301|redirect|redire|consolid/i))).map(row=>({url:pick(row,['URL actual','URL','Address'])||row.url,priority:pick(row,['Prioridad','Prioridad SEO'])||row.priority,action:pick(row,['Acción','Acción sugerida','Action'])||row.action,status:pick(row,['HTTP Status','Status Code','Status'])||row.status,target:pick(row,['Destino','URL nueva','Target URL'])||row.target,issues:pick(row,['Issues','Problemas'])||row.issues,recommendation:pick(row,['Recomendación','Notas SEO','Notes'])||'Revisar destino final antes del deploy'})).filter(r=>r.url);
const top=(topRows.length?topRows:master.slice().sort((a,b)=>num(b.clicks)-num(a.clicks)).slice(0,40)).map(row=>({url:pick(row,['URL','URL actual','Landing Page'])||row.url,clicks:pick(row,['Clicks','Clics','Clics GSC'])||row.clicks,impressions:pick(row,['Impressions','Impresiones','Impresiones GSC'])||row.impressions,position:pick(row,['Position','Posición','Posición GSC'])||row.position,kw:pick(row,['Keyword','KW detectada','Keyword principal'])||row.kw,title:pick(row,['Title','Title actual','Meta title actual'])||row.title,notes:pick(row,['Notas','Notas SEO','Notes'])||'Proteger URL durante migración'})).filter(r=>r.url);
const issues=(issueRows.length?issueRows:buildIssuesFromMaster(master)).map(row=>({issue:pick(row,['Issue','Problema','Issues','Name'])||row.issue,count:pick(row,['Count','Cantidad','URLs','Total'])||row.count,recommendation:pick(row,['Recomendación','Recommendation'])||row.recommendation})).filter(r=>r.issue);
const checklist=(checklistRows.length?checklistRows:defaultChecklist()).map(row=>({phase:pick(row,['Fase','Phase'])||row.phase,task:pick(row,['Tarea','Task'])||row.task,owner:pick(row,['Owner','Responsable'])||row.owner,status:pick(row,['Status','Estado'])||row.status||'Pendiente',notes:pick(row,['Notas','Notes'])||row.notes})).filter(r=>r.task);
return{master,keywords,redirects,top,issues,checklist}}
function buildIssuesFromMaster(master){const map={};master.forEach(r=>norm(r.issues).split(/[,;|]/).map(x=>x.trim()).filter(Boolean).forEach(i=>map[i]=(map[i]||0)+1));return Object.entries(map).map(([issue,count])=>({issue,count})).sort((a,b)=>b.count-a.count)}
function defaultChecklist(){return[{phase:'Fase 1',task:'Exportar URLs indexadas y tráfico GSC',owner:'SEO',status:'Pendiente',notes:'Base para proteger tráfico'},{phase:'Fase 1',task:'Completar URL Mapping Master',owner:'SEO',status:'Pendiente',notes:'URL vieja → URL nueva'},{phase:'Fase 2',task:'Implementar metadata en Astro',owner:'Dev/SEO',status:'Pendiente',notes:'Title, description, canonical, OG'},{phase:'Fase 2',task:'Implementar schema JSON-LD',owner:'Dev/SEO',status:'Pendiente',notes:'Organization, Service, Article, FAQ'},{phase:'Fase 3',task:'Validar 0 URLs críticas en 404',owner:'SEO/Dev',status:'Pendiente',notes:'Screaming Frog o similar'},{phase:'Fase 4',task:'Reenviar sitemap en GSC',owner:'SEO',status:'Pendiente',notes:'Post switch'},{phase:'Fase 5',task:'Monitoreo GSC diario primera semana',owner:'SEO',status:'Pendiente',notes:'Clicks, impresiones, cobertura'}]}
function boot(){filtered=[...DATA.master];initKPIs();initCharts();fillFilters();renderMaster();renderMetadata();renderKeywords();renderRedirects();renderTop();renderKanban()}
function initKPIs(){const total=DATA.master.length,alta=DATA.master.filter(r=>norm(r.priority).toLowerCase().includes('alta')).length,redirects=DATA.redirects.length,metadata=DATA.master.filter(r=>norm(r.metaStatus).toLowerCase().match(/optim|falta/)).length,protectedUrls=DATA.top.length,clicks=sum(DATA.master,'clicks'),impressions=sum(DATA.master,'impressions');const k=[['URLs controladas',total,'Master SEO completo'],['Prioridad alta',alta,'URLs críticas'],['URLs protegidas',protectedUrls,'No romper'],['Redirects',redirects,'301/consolidación'],['Metadata pendiente',metadata,'Titles/descriptions'],['Clics GSC',fmt.format(clicks),fmt.format(impressions)+' impresiones']];document.getElementById('kpis').innerHTML=k.map(x=>`<div class="card kpi"><div class="label">${x[0]}</div><div class="num">${x[1]}</div><div class="hint">${x[2]}</div></div>`).join('')}
function donut(id,entries){const total=entries.reduce((a,e)=>a+e[1],0)||1;let start=0;const cx=130,cy=130,r=88,sw=34;function arc(value,i){const frac=value/total,end=start+frac*360,large=frac>.5?1:0,a1=(start-90)*Math.PI/180,a2=(end-90)*Math.PI/180,x1=cx+r*Math.cos(a1),y1=cy+r*Math.sin(a1),x2=cx+r*Math.cos(a2),y2=cy+r*Math.sin(a2);start=end;return`<path d="M ${x1} ${y1} A ${r} ${r} 0 ${large} 1 ${x2} ${y2}" fill="none" stroke="${colors[i%colors.length]}" stroke-width="${sw}" stroke-linecap="round"/>`}const paths=entries.map((e,i)=>arc(e[1],i)).join('');const legend=entries.map((e,i)=>`<span class="pill gray"><span class="dot" style="background:${colors[i%colors.length]}"></span>${esc(e[0])} · ${fmt.format(e[1])}</span>`).join('');document.getElementById(id).innerHTML=`<div style="display:flex;gap:20px;align-items:center;flex-wrap:wrap"><svg width="260" height="260" viewBox="0 0 260 260"><circle cx="130" cy="130" r="88" fill="none" stroke="#e2e8f0" stroke-width="34"/>${paths}<text x="130" y="124" text-anchor="middle" style="font-size:28px;font-weight:900;fill:#0f172a">${fmt.format(total)}</text><text x="130" y="148" text-anchor="middle" style="font-size:12px;fill:#64748b">URLs</text></svg><div class="legend">${legend}</div></div>`}
function barChart(id,entries,opt={}){entries=entries.slice(0,opt.limit||9);const max=Math.max(...entries.map(e=>e[1]),1);const rows=entries.map((e,i)=>{const w=Math.max(4,Math.round((e[1]/max)*70)),y=26+i*28;return`<text x="0" y="${y}" class="bar-label">${esc(e[0]).slice(0,38)}</text><rect x="190" y="${y-14}" width="${w}%" height="18" rx="8" fill="${colors[i%colors.length]}"></rect><text x="710" y="${y}" class="bar-value">${fmt.format(e[1])}</text>`}).join('');document.getElementById(id).innerHTML=`<svg class="chart" viewBox="0 0 760 ${Math.max(270,entries.length*30+28)}" preserveAspectRatio="xMinYMin meet">${rows}</svg>`}
function initCharts(){donut('actionChart',countBy(DATA.master,'action'));donut('priorityChart',countBy(DATA.master,'priority'));donut('metadataChart',countBy(DATA.master,r=>r.metaStatus||'Sin dato'));barChart('issuesChart',DATA.issues.map(r=>[r.issue,num(r.count)]),{limit:9});const total=DATA.master.length,high=DATA.master.filter(r=>norm(r.priority).toLowerCase().includes('alta')).length,redirects=DATA.redirects.length,metaOpt=DATA.master.filter(r=>norm(r.metaStatus).toLowerCase().match(/optim|falta/)).length;document.getElementById('executiveSummary').innerHTML=`El tablero controla <strong>${fmt.format(total)} URLs</strong>. Hay <strong>${fmt.format(high)} URLs de prioridad alta</strong> que deben protegerse antes del switch a Astro. Se detectan <strong>${fmt.format(redirects)} redirecciones</strong> a revisar para evitar cadenas y pérdida de autoridad. Además, <strong>${fmt.format(metaOpt)} URLs tienen metadata pendiente u optimizable</strong>.`}
function fillFilters(){if(!filtersReady){['filterPriority','filterAction','filterType','filterMeta'].forEach(id=>{const el=document.getElementById(id);el.innerHTML=el.options[0].outerHTML});[['filterPriority','priority'],['filterAction','action'],['filterType','type'],['filterMeta','metaStatus']].forEach(([id,key])=>{const el=document.getElementById(id);countBy(DATA.master,key).map(e=>e[0]).forEach(v=>el.insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(v)}</option>`));el.onchange=applyFilters});document.getElementById('search').oninput=applyFilters;filtersReady=true}}
function applyFilters(){const q=norm(document.getElementById('search').value).toLowerCase(),p=norm(document.getElementById('filterPriority').value),a=norm(document.getElementById('filterAction').value),t=norm(document.getElementById('filterType').value),m=norm(document.getElementById('filterMeta').value);filtered=DATA.master.filter(r=>{const blob=Object.values(r).join(' ').toLowerCase();return(!q||blob.includes(q))&&(!p||r.priority===p)&&(!a||r.action===a)&&(!t||r.type===t)&&(!m||r.metaStatus===m)});renderMaster()}
function resetFilters(){['search','filterPriority','filterAction','filterType','filterMeta'].forEach(id=>document.getElementById(id).value='');filtered=[...DATA.master];renderMaster()}
function renderMaster(){document.getElementById('tableCount').textContent=`${fmt.format(filtered.length)} URLs visibles de ${fmt.format(DATA.master.length)}`;document.querySelector('#masterTable tbody').innerHTML=filtered.slice(0,800).map(r=>`<tr><td><a class="url" href="${esc(r.url)}" target="_blank">${esc(hostPath(r.url))}</a><div class="muted">${esc(r.title).slice(0,90)}</div></td><td>${esc(r.type)}</td><td>${pill(r.priority,priorityClass(r.priority))}</td><td>${pill(r.action,'blue')}</td><td>${esc(r.status)}</td><td>${fmt.format(num(r.clicks))}</td><td>${fmt.format(num(r.impressions))}</td><td>${esc(r.kw)}</td><td>${pill(r.metaStatus||'—',norm(r.metaStatus).match(/optim|falta/i)?'media':'gray')}</td><td>${esc(r.issues).slice(0,120)}</td><td>${esc(r.qa)}</td></tr>`).join('')}
function renderMetadata(){document.querySelector('#metadataTable tbody').innerHTML=DATA.master.filter(r=>r.title||r.description||r.metaStatus).slice(0,800).map(r=>`<tr><td><a class="url" href="${esc(r.url)}" target="_blank">${esc(hostPath(r.url))}</a></td><td>${esc(r.title)}</td><td>${esc(r.titleLen)}</td><td>${esc(r.description)}</td><td>${esc(r.descriptionLen)}</td><td>${pill(r.metaStatus||'—',norm(r.metaStatus).match(/optim|falta/i)?'media':'gray')}</td><td>${esc(r.schema)}</td></tr>`).join('')}
function renderKeywords(){document.querySelector('#keywordTable tbody').innerHTML=DATA.keywords.slice(0,800).map(r=>`<tr><td><a class="url" href="${esc(r.url)}" target="_blank">${esc(hostPath(r.url))}</a></td><td>${pill(r.priority,priorityClass(r.priority))}</td><td><strong>${esc(r.kw)}</strong></td><td>${esc(r.intent)}</td><td>${esc(r.kwPosition)}</td><td>${fmt.format(num(r.volume))}</td><td>${fmt.format(num(r.clicks))}</td><td>${fmt.format(num(r.impressions))}</td><td>${esc(r.target)}</td></tr>`).join('')}
function renderRedirects(){document.querySelector('#redirectTable tbody').innerHTML=DATA.redirects.slice(0,800).map(r=>`<tr><td><a class="url" href="${esc(r.url)}" target="_blank">${esc(hostPath(r.url))}</a></td><td>${pill(r.priority,priorityClass(r.priority))}</td><td>${pill(r.action,'blue')}</td><td>${esc(r.status)}</td><td>${esc(r.target||'Definir destino')}</td><td>${esc(r.issues)}</td><td>${esc(r.recommendation)}</td></tr>`).join('')}
function renderTop(){document.querySelector('#topTable tbody').innerHTML=DATA.top.slice(0,100).map(r=>`<tr><td><a class="url" href="${esc(r.url)}" target="_blank">${esc(hostPath(r.url))}</a></td><td>${fmt.format(num(r.clicks))}</td><td>${fmt.format(num(r.impressions))}</td><td>${esc(r.position)}</td><td><strong>${esc(r.kw)}</strong></td><td>${esc(r.title)}</td><td>${esc(r.notes)}</td></tr>`).join('')}
function renderKanban(){const statuses=['Pendiente','En progreso','En revisión','Aprobado'],container=document.getElementById('kanban');container.innerHTML=statuses.map(s=>`<div class="lane"><h4>${s}</h4><div data-lane="${s}"></div></div>`).join('');DATA.checklist.forEach(t=>{const current=statuses.includes(t.status)?t.status:'Pendiente';const html=`<div class="task"><div class="phase">${esc(t.phase)}</div><p><strong>${esc(t.task)}</strong></p><p class="muted">${esc(t.owner)} · ${esc(t.notes)}</p><span class="pill ${current==='Aprobado'?'baja':current==='En progreso'?'blue':current==='En revisión'?'media':'gray'}">${esc(current)}</span></div>`;(container.querySelector(`[data-lane="${current}"]`)||container.querySelector(`[data-lane="Pendiente"]`)).insertAdjacentHTML('beforeend',html)});const pct=Math.round((DATA.checklist.filter(t=>t.status==='Aprobado').length/Math.max(DATA.checklist.length,1))*100);document.getElementById('migrationReadiness').textContent=pct+'%';document.getElementById('readyBar').style.width=pct+'%'}
function downloadCSV(){const headers=['url','type','priority','action','status','clicks','impressions','kw','metaStatus','issues','qa'];const csv=[headers.join(',')].concat(filtered.map(r=>headers.map(h=>`"${norm(r[h]).replace(/"/g,'""')}"`).join(','))).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='hitocean_vista_filtrada_mapping.csv';a.click()}
document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('nav a').forEach(x=>x.classList.remove('active'));a.classList.add('active')}));loadData();
